name: Simple Kernel Builder

on:
  workflow_dispatch: # Se déclenche manuellement
  push:
    branches: [ main ] # Se déclenche sur push vers main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate timestamp tag
      id: timestamp
      run: |
        DATE_TAG=$(date +'build-%Y.%m.%d-%H%M')
        echo "tag_name=$DATE_TAG" >> $GITHUB_OUTPUT
        echo "Created tag: $DATE_TAG"
        
    - name: Create git tag
      run: |
        git tag ${{ steps.timestamp.outputs.tag_name }}
        git push origin ${{ steps.timestamp.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
        zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev \
        libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
        
    - name: Build kernels
      run: |
        chmod +x build.sh
        # Build pour tous les modèles
        for model in d1 d1xks d2s d2x d2xks; do
          echo "Building for $model"
          ./build.sh --model $model --ksu Y --debug N
        done
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-builds-${{ steps.timestamp.outputs.tag_name }}
        path: build/out/**/ExtremeKernel*.zip